# Generated by Django 4.0.3 on 2022-10-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
